{
 "title": "Prebuilds",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "template",
    "label": "Template",
    "query": {
     "query": "label_values(coderd_prebuilt_workspaces_desired,template_name)"
    }
   },
   {
    "name": "preset",
    "label": "Preset",
    "query": {
     "query": "label_values(coderd_prebuilt_workspaces_desired{template_name=~\"$template\"},preset_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current: Global",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(coderd_prebuilt_workspaces_desired) by (template_name, preset_name)) or vector(0)",
     "legendFormat": "Desired"
    },
    {
     "expr": "sum(max(coderd_prebuilt_workspaces_running) by (template_name, preset_name)) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(max(coderd_prebuilt_workspaces_eligible) by (template_name, preset_name)) or vector(0)",
     "legendFormat": "Eligible"
    }
   ]
  },
  {
   "title": "All Time: Global",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (template_name, preset_name) (coderd_prebuilt_workspaces_created_total)) or vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "sum(max by (template_name, preset_name) (coderd_prebuilt_workspaces_failed_total)) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(max by (template_name, preset_name) (coderd_prebuilt_workspaces_claimed_total)) or vector(0)",
     "legendFormat": "Claimed"
    }
   ]
  },
  { "title": "$preset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "preset" },
  {
   "title": "All Time: $preset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coderd_prebuilt_workspaces_created_total{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_failed_total{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_claimed_total{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Claimed"
    }
   ]
  },
  {
   "title": "Pool Operations: $preset",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "floor(max(increase(coderd_prebuilt_workspaces_created_total{template_name=~\"$template\", preset_name=~\"$preset\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "floor(max(increase(coderd_prebuilt_workspaces_failed_total{template_name=~\"$template\", preset_name=~\"$preset\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "floor(max(increase(coderd_prebuilt_workspaces_claimed_total{template_name=~\"$template\", preset_name=~\"$preset\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Claimed"
    }
   ]
  },
  {
   "title": "Pool Capacity: $preset",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "max(coderd_prebuilt_workspaces_desired{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Desired"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_running{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_eligible{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Eligible"
    }
   ]
  },
  {
   "title": "Current: $preset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coderd_prebuilt_workspaces_desired{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Desired"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_running{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "max(coderd_prebuilt_workspaces_eligible{template_name=~\"$template\", preset_name=~\"$preset\"}) or vector(0)",
     "legendFormat": "Eligible"
    }
   ]
  },
  {
   "title": "All Time: Regular vs Prebuilt",
   "type": "stat",
   "description": "Compares the total number of regular workspace creations to prebuilt workspace claims to date.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (template_name, preset_name) (\n  coderd_workspace_creation_total{\n    template_name=~\"$template\", preset_name=~\"$preset\"\n  }\n)) or vector(0)",
     "legendFormat": "Regular workspaces created"
    },
    {
     "expr": "sum(max by (template_name, preset_name) (\n  coderd_prebuilt_workspaces_claimed_total{\n    template_name=~\"$template\", preset_name=~\"$preset\"\n  }\n)) or vector(0)\n",
     "legendFormat": "Prebuilt workspaces claimed"
    }
   ]
  },
  {
   "title": "Workspace Build Latency p50",
   "type": "timeseries",
   "description": "Median (p50) build time in seconds for Regular Workspace Creation, Prebuilt Workspace Creation, and Prebuilt Workspace Claim",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\n  sum(\n    coderd_workspace_creation_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\", type=\"regular\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Regular Creation"
    },
    {
     "expr": "histogram_quantile(0.5,\n  sum(\n    coderd_workspace_creation_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\", type=\"prebuild\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Prebuild Creation"
    },
    {
     "expr": "histogram_quantile(0.5,\n  sum(\n    coderd_prebuilt_workspace_claim_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Prebuild Claim"
    }
   ]
  },
  {
   "title": "Workspace Build Latency p95",
   "type": "timeseries",
   "description": "95th-percentile (p95) build time in seconds for Regular Workspace Creation, Prebuilt Workspace Creation, and Prebuilt Workspace Claim.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    coderd_workspace_creation_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\", type=\"regular\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Regular Creation"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    coderd_workspace_creation_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\", type=\"prebuild\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Prebuild Creation"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    coderd_prebuilt_workspace_claim_duration_seconds{\n      template_name=~\"$template\", preset_name=~\"$preset\"\n    }\n  )\n)\nor vector(0)",
     "legendFormat": "Prebuild Claim"
    }
   ]
  },
  {
   "title": "All Time: Prebuilds Usage %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  100 *\n  (\n    sum(\n      coderd_prebuilt_workspaces_claimed_total{\n        template_name=\"$template\", preset_name=\"$preset\"\n      }\n    ) or vector(0)\n  )\n  /\n  clamp_min(\n    ( \n      sum(\n        coderd_prebuilt_workspaces_claimed_total{\n          template_name=\"$template\", preset_name=\"$preset\"\n        }\n      ) or vector(0))\n    +\n    (\n      sum(\n        coderd_workspace_creation_total{\n          template_name=\"$template\", preset_name=\"$preset\"\n        }\n      ) or vector(0)),\n    1\n  ),\n  100\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}